### ISSUE TITLE
Better error handling for HTTP responses

### ISSUE THREAD

**Issue by jjsendor** [Yelp/threat_intel#46]
It seems that Threat Intel does not handle very well HTTP error responses, e.g. **403 Forbidden**.
They are rather ignored silently.
Some error handling, e.g. throwing an exception, might be a better way of dealing with these situations.

**Comment by megancarney** [comment]
If you point me to the sections of code you're worried about, I can take a look too.

**Comment by jjsendor** [comment]
So when I was investigating this recent errors in OSXCollector LookupDomainsFilter test I was supplying wrong OpenDNS API key and I was getting 403 from their service.
This apparently was treated like an empty response because it was getting filtered out by [this list comprehension](https://github.com/Yelp/threat_intel/blob/master/threat_intel/util/http.py#L282).

But to be very honest I have no idea how to distinguish 403 in this case with some other empty responses that were particularly  annoying and made you add the retry thing.

**Comment by megancarney** [comment]
Would it make sense to break the loop and raise a connection error if response.status_code == 403? I think it's safe to assume that if authentication is the problem, retrying won't make the request succeed.

**Comment by jjsendor** [comment]
I think this is a great idea :)

**Comment by jjsendor** [comment]
Closed in #54.
