### ISSUE TITLE
Setup autodeploy to PyPI through Travis

### ISSUE THREAD

**Issue by jjsendor** [Yelp/threat_intel#51]
[Here](https://github.com/Yelp/paasta/commit/9fa486069cf70b78f43f048ba889fd6870d16e49) is an example how to do it from the PaaSTA GitHub repo.

**Comment by jjsendor** [comment]
@tomelm: would you like to take a stab at this? It worked pretty sweet for [osxcollector](https://github.com/Yelp/osxcollector/pull/149) and [osxcollector_output_filters](https://github.com/Yelp/osxcollector_output_filters/pull/37) repos.

**Comment by tomelm** [comment]
Yep, I'll do this next week!

**Comment by jjsendor** [comment]
Hi @tomelm! Any updates on this one?

**Comment by piax93** [comment]
Completed in df80203ff2e1a2ff9ce6ee8d05416591f21dc340
